RUN_MODE: debug

## app
PAGE_SIZE: 10
JWT_SECRET: 123&*^*SA

## server
HTTP_PORT: 8000
READ_TIMEOUT: 30
WRITE_TIMEOUT: 40

## database
TYPE: mysql
USER: root
PASSWORD: rootroot
HOST: 81.69.219.4:53306
NAME: blog
TABLE_PREFIX: blog_